#include <stddef.h>
#include <stdint.h>

#include "cypdf_operators.h"
#include "cypdf_utils.h"



/* Operator lookup table */
static const char* operator_names[CYPDF_OPERATOR_COUNT] = {
    [CYPDF_OPERATOR_PATH_BEGIN] = CYPDF_OPERATOR_PATH_BEGIN_N,
    [CYPDF_OPERATOR_PATH_LINESEG] = CYPDF_OPERATOR_PATH_LINESEG_N,
    [CYPDF_OPERATOR_PATH_CBEZIER] = CYPDF_OPERATOR_PATH_CBEZIER_N,
    [CYPDF_OPERATOR_PATH_VBEZIER] = CYPDF_OPERATOR_PATH_VBEZIER_N,
    [CYPDF_OPERATOR_PATH_YBEZIER] = CYPDF_OPERATOR_PATH_YBEZIER_N,
    [CYPDF_OPERATOR_PATH_CLOSE] = CYPDF_OPERATOR_PATH_CLOSE_N,
    [CYPDF_OPERATOR_PATH_RECT] = CYPDF_OPERATOR_PATH_RECT_N,
    [CYPDF_OPERATOR_PATH_STROKE] = CYPDF_OPERATOR_PATH_STROKE_N,
    [CYPDF_OPERATOR_PATH_CLOSE_STROKE] = CYPDF_OPERATOR_PATH_CLOSE_STROKE_N,
    [CYPDF_OPERATOR_PATH_NWNRFILL] = CYPDF_OPERATOR_PATH_NWNRFILL_N,
    [CYPDF_OPERATOR_PATH_EORFILL] = CYPDF_OPERATOR_PATH_EORFILL_N,
    [CYPDF_OPERATOR_PATH_NWNRFILL_STROKE] = CYPDF_OPERATOR_PATH_NWNRFILL_STROKE_N,
    [CYPDF_OPERATOR_PATH_EORFILL_STROKE] CYPDF_OPERATOR_PATH_EORFILL_STROKE_N,
    [CYPDF_OPERATOR_PATH_CLOSE_NWNRFILL_STROKE] = CYPDF_OPERATOR_PATH_CLOSE_NWNRFILL_STROKE_N,
    [CYPDF_OPERATOR_PATH_CLOSE_EORFILL_STROKE] = CYPDF_OPERATOR_PATH_CLOSE_EORFILL_STROKE_N,
    [CYPDF_OPERATOR_PATH_END] = CYPDF_OPERATOR_PATH_END_N,
    [CYPDF_OPERATOR_PATH_NWNRCLIP] = CYPDF_OPERATOR_PATH_NWNRCLIP_N,
    [CYPDF_OPERATOR_PATH_EORCLIP] = CYPDF_OPERATOR_PATH_EORCLIP_N,
    [CYPDF_OPERATOR_GFX_STATE_SAVE] = CYPDF_OPERATOR_GFX_STATE_SAVE_N,
    [CYPDF_OPERATOR_GFX_STATE_RESTORE] = CYPDF_OPERATOR_GFX_STATE_RESTORE_N,
    [CYPDF_OPERATOR_GFX_STATE_MATRIX] = CYPDF_OPERATOR_GFX_STATE_MATRIX_N,
    [CYPDF_OPERATOR_GFX_STATE_LINE_WIDTH] = CYPDF_OPERATOR_GFX_STATE_LINE_WIDTH_N,
    [CYPDF_OPERATOR_GFX_STATE_LINE_CAP] = CYPDF_OPERATOR_GFX_STATE_LINE_CAP_N,
    [CYPDF_OPERATOR_GFX_STATE_LINE_JOIN] = CYPDF_OPERATOR_GFX_STATE_LINE_JOIN_N,
    [CYPDF_OPERATOR_GFX_STATE_MITER_LIMIT] = CYPDF_OPERATOR_GFX_STATE_MITER_LIMIT_N,
    [CYPDF_OPERATOR_GFX_STATE_DASH_PATTERN] = CYPDF_OPERATOR_GFX_STATE_DASH_PATTERN_N,
    [CYPDF_OPERATOR_GFX_STATE_INTENT] = CYPDF_OPERATOR_GFX_STATE_INTENT_N,
    [CYPDF_OPERATOR_GFX_STATE_FLATNESS] = CYPDF_OPERATOR_GFX_STATE_FLATNESS_N,
    [CYPDF_OPERATOR_GFX_STATE_EXTGSTATE] = CYPDF_OPERATOR_GFX_STATE_EXTGSTATE_N,
    [CYPDF_OPERATOR_COLOR_SPACE_STROKING] = CYPDF_OPERATOR_COLOR_SPACE_STROKING_N,
    [CYPDF_OPERATOR_COLOR_SPACE_NONSTROKING] = CYPDF_OPERATOR_COLOR_SPACE_NONSTROKING_N,
    [CYPDF_OPERATOR_COLOR_STROKING] = CYPDF_OPERATOR_COLOR_STROKING_N,
    [CYPDF_OPERATOR_COLOR_STROKING_EXT] = CYPDF_OPERATOR_COLOR_STROKING_EXT_N,
    [CYPDF_OPERATOR_COLOR_NONSTROKING] = CYPDF_OPERATOR_COLOR_NONSTROKING_N,
    [CYPDF_OPERATOR_COLOR_NONSTROKING_EXT] = CYPDF_OPERATOR_COLOR_NONSTROKING_EXT_N,
    [CYPDF_OPERATOR_COLOR_STROKING_GRAY] = CYPDF_OPERATOR_COLOR_STROKING_GRAY_N,
    [CYPDF_OPERATOR_COLOR_NONSTROKING_GRAY] = CYPDF_OPERATOR_COLOR_NONSTROKING_GRAY_N,
    [CYPDF_OPERATOR_COLOR_STROKING_RGB] = CYPDF_OPERATOR_COLOR_STROKING_RGB_N,
    [CYPDF_OPERATOR_COLOR_NONSTROKING_RGB] = CYPDF_OPERATOR_COLOR_NONSTROKING_RGB_N,
    [CYPDF_OPERATOR_COLOR_STROKING_CMYK] = CYPDF_OPERATOR_COLOR_STROKING_CMYK_N,
    [CYPDF_OPERATOR_COLOR_NONSTROKING_CMYK] = CYPDF_OPERATOR_COLOR_NONSTROKING_CMYK_N
};


CYPDF_Operator* CYPDF_NewOperator(const uint32_t type, const void* const* const operands, size_t operand_count) {
    CYPDF_Operator* operator = (CYPDF_Operator*)CYPDF_smalloc(sizeof(CYPDF_Operator));

    if (operator) {
        operator->type = type;
        operator->operands = operands;

        if (!operands) {
            operand_count = 0;
        }
        operator->operand_count = operand_count;
    }

    return operator;
}

void CYPDF_FreeOperator(CYPDF_Operator* operator) {
    if (operator) {
        for (size_t i = 0; i < operator->operand_count; ++i) {
            free(operator->operands[i]);
        }
        free(operator->operands);

        free(operator);
    }
}

const char* CYPDF_OperatorGetName(const CYPDF_Operator* const operator) {
    char* name = NULL;

    if (operator) {
        name = operator_names[operator->type];
    }

    return name;
}

void CYPDF_OperatorAppendOperand(CYPDF_Operator* const operator, const void* const operand) {
    if (operator && operand) {
        operator->operands = CYPDF_srealloc(operator->operands, (operator->operand_count + 1) * sizeof(void*));
        operator->operands[operator->operand_count] = operand;
        ++operator->operand_count;
    }
}
