#include <stdbool.h>
#include <stdlib.h>

#include "cypdf_operators.h"
#include "cypdf_list.h"
#include "cypdf_log.h"
#include "cypdf_memory.h"
#include "cypdf_object.h"
#include "cypdf_print.h"
#include "cypdf_types.h"



/* Operator lookup table */
static char* operators[CYPDF_OPERATOR_COUNT] = {
    [CYPDF_PATH_BEGIN] = CYPDF_OP_PATH_BEGIN,
    [CYPDF_PATH_LINESEG] = CYPDF_OP_PATH_LINESEG,
    [CYPDF_PATH_CBEZIER] = CYPDF_OP_PATH_CBEZIER,
    [CYPDF_PATH_VBEZIER] = CYPDF_OP_PATH_VBEZIER,
    [CYPDF_PATH_YBEZIER] = CYPDF_OP_PATH_YBEZIER,
    [CYPDF_PATH_CLOSE] = CYPDF_OP_PATH_CLOSE,
    [CYPDF_PATH_RECT] = CYPDF_OP_PATH_RECT,
    [CYPDF_PATH_STROKE] = CYPDF_OP_PATH_STROKE,
    [CYPDF_PATH_CLOSE_STROKE] = CYPDF_OP_PATH_CLOSE_STROKE,
    [CYPDF_PATH_NWFILL] = CYPDF_OP_PATH_NWFILL,
    [CYPDF_PATH_EOFILL] = CYPDF_OP_PATH_EOFILL,
    [CYPDF_PATH_NWFILL_STROKE] = CYPDF_OP_PATH_NWFILL_STROKE,
    [CYPDF_PATH_EOFILL_STROKE] = CYPDF_OP_PATH_EOFILL_STROKE,
    [CYPDF_PATH_CLOSE_NWFILL_STROKE] = CYPDF_OP_PATH_CLOSE_NWFILL_STROKE,
    [CYPDF_PATH_CLOSE_EOFILL_STROKE] = CYPDF_OP_PATH_CLOSE_EOFILL_STROKE,
    [CYPDF_PATH_END] = CYPDF_OP_PATH_END,
    [CYPDF_PATH_NWCLIP] = CYPDF_OP_PATH_NWCLIP,
    [CYPDF_PATH_EOCLIP] = CYPDF_OP_PATH_EOCLIP,
    [CYPDF_STATE_SAVE] = CYPDF_OP_STATE_SAVE,
    [CYPDF_STATE_RESTORE] = CYPDF_OP_STATE_RESTORE,
    [CYPDF_STATE_MATRIX] = CYPDF_OP_STATE_MATRIX,
    [CYPDF_STATE_LINE_WIDTH] = CYPDF_OP_STATE_LINE_WIDTH,
    [CYPDF_STATE_LINE_CAP] = CYPDF_OP_STATE_LINE_CAP,
    [CYPDF_STATE_LINE_JOIN] = CYPDF_OP_STATE_LINE_JOIN,
    [CYPDF_STATE_MITER_LIMIT] = CYPDF_OP_STATE_MITER_LIMIT,
    [CYPDF_STATE_DASH_PATTERN] = CYPDF_OP_STATE_DASH_PATTERN,
    [CYPDF_STATE_INTENT] = CYPDF_OP_STATE_INTENT,
    [CYPDF_STATE_FLATNESS] = CYPDF_OP_STATE_FLATNESS,
    [CYPDF_STATE_EXTGSTATE] = CYPDF_OP_STATE_EXTGSTATE,
    [CYPDF_C_SPACE_STROKING] = CYPDF_OP_C_SPACE_STROKING,
    [CYPDF_C_SPACE_NONSTROKING] = CYPDF_OP_C_SPACE_NONSTROKING,
    [CYPDF_C_STROKING] = CYPDF_OP_C_STROKING,
    [CYPDF_C_STROKING_EXT] = CYPDF_OP_C_STROKING_EXT,
    [CYPDF_C_NONSTROKING] = CYPDF_OP_C_NONSTROKING,
    [CYPDF_C_NONSTROKING_EXT] = CYPDF_OP_C_NONSTROKING_EXT,
    [CYPDF_C_STROKING_GRAY] = CYPDF_OP_C_STROKING_GRAY,
    [CYPDF_C_NONSTROKING_GRAY] = CYPDF_OP_C_NONSTROKING_GRAY,
    [CYPDF_C_STROKING_RGB] = CYPDF_OP_C_STROKING_RGB,
    [CYPDF_C_NONSTROKING_RGB] = CYPDF_OP_C_NONSTROKING_RGB,
    [CYPDF_C_STROKING_CMYK] = CYPDF_OP_C_STROKING_CMYK,
    [CYPDF_C_NONSTROKING_CMYK] = CYPDF_OP_C_NONSTROKING_CMYK,
    [CYPDF_TEXT_BEGIN] = CYPDF_OP_TEXT_BEGIN,
    [CYPDF_TEXT_END] = CYPDF_OP_TEXT_END,
    [CYPDF_TEXT_CHAR_SPACE] = CYPDF_OP_TEXT_CHAR_SPACE,
    [CYPDF_TEXT_WORD_SPACE] = CYPDF_OP_TEXT_WORD_SPACE,
    [CYPDF_TEXT_SCALE] = CYPDF_OP_TEXT_SCALE,
    [CYPDF_TEXT_LEADING] = CYPDF_OP_TEXT_LEADING,
    [CYPDF_TEXT_FONT] = CYPDF_OP_TEXT_FONT,
    [CYPDF_TEXT_RENDER] = CYPDF_OP_TEXT_RENDER,
    [CYPDF_TEXT_RISE] = CYPDF_OP_TEXT_RISE,
    [CYPDF_TEXT_OFFSET] = CYPDF_OP_TEXT_OFFSET,
    [CYPDF_TEXT_OFFSET_PERSISTENT] = CYPDF_OP_TEXT_OFFSET_PERSISTENT,
    [CYPDF_TEXT_MATRIX] = CYPDF_OP_TEXT_MATRIX,
    [CYPDF_TEXT_NEXT_LINE] = CYPDF_OP_TEXT_NEXT_LINE,
    [CYPDF_TEXT_SHOW] = CYPDF_OP_TEXT_SHOW,
    [CYPDF_TEXT_SHOW_NEXT_LINE] = CYPDF_OP_TEXT_SHOW_NEXT_LINE,
    [CYPDF_TEXT_MOD_SHOW_NEXT_LINE] = CYPDF_OP_TEXT_MOD_SHOW_NEXT_LINE,
    [CYPDF_TEXT_SHOW_MULT] = CYPDF_OP_TEXT_SHOW_MULT
};


CYPDF_Operator* CYPDF_NewOperator(const enum CYPDF_OPERATOR_TYPE type) {
    CYPDF_TRACE;

    CYPDF_Operator* operator = (CYPDF_Operator*)CYPDF_malloc(sizeof(CYPDF_Operator));

    operator->type = type;
    operator->operand_list = CYPF_NewList(CYPDF_LIST_DEFAULT_BLOCK_SIZE);

    return operator;
}

void CYPDF_FreeOperator(CYPDF_Operator* operator) {
    CYPDF_TRACE;

    CYPDF_FreeList(operator->operand_list);

    free(operator);
}

void CYPDF_PrintOperator(CYPDF_Channel* const channel, const CYPDF_Operator* const operator) {
    CYPDF_TRACE;

    for (size_t i = 0; i < CYPDF_ListLength(operator->operand_list); ++i) {
        CYPDF_PrintObjDirect(channel, CYPDF_ListAtIndex(operator->operand_list, i));
        CYPDF_ChannelPrint(channel, " ");
    }
    
    CYPDF_ChannelPrint(channel, "%s", CYPDF_OperatorGetKey(operator));
}


char* CYPDF_OperatorGetKey(const CYPDF_Operator* const operator) {
    CYPDF_TRACE;

    return operators[operator->type];
}

void CYPDF_OperatorAppend(CYPDF_Operator* const operator, CYPDF_Object* const operand) {
    CYPDF_TRACE;

    CYPFD_ListAppend(operator->operand_list, operand);
}


bool CYPDF_OperatorIsPainting(const CYPDF_Operator* const restrict operator) {
    CYPDF_TRACE;

    return operator->type >= CYPDF_PATH_STROKE && operator->type <= CYPDF_PATH_END;
}
